name: sam4d
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py312h8285ef7_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=hbd61a6d_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312h5253ce2_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=8_cp312
  - pyzmq=27.0.2=py312hbd2df5a_1
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.2=py312h4c3975b_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - addict==2.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argcomplete==3.6.3
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dash==3.3.0
      - decorator==4.4.2
      - depth-anything-3==0.0.0
      - distlib==0.4.0
      - e3nn==0.5.8
      - einops==0.8.1
      - evo==1.34.0
      - fastapi==0.121.3
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gputil==1.4.0
      - gsplat==1.5.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.5
      - identify==2.6.15
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jaxtyping==0.3.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lz4==4.4.5
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - narwhals==2.12.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - networkx==3.5
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numexpr==2.14.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - pandas==2.3.3
      - pillow==12.0.0
      - pillow-heif==1.1.1
      - plotly==6.5.0
      - plyfile==1.1.3
      - pre-commit==4.4.0
      - proglog==0.1.12
      - pycolmap==3.13.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - retrying==1.4.2
      - rich==14.2.0
      - rosbags==0.11.0
      - rpds-py==0.29.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.50.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - trimesh==4.9.0
      - triton==3.1.0
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - virtualenv==20.35.4
      - wadler-lindig==0.1.7
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - xformers==0.0.29.post1
      - zstandard==0.25.0
prefix: /home/yanglei/anaconda3/envs/sam4d
